--Import student-mat.csv using pgAdmin into the following table.

CREATE TABLE student_achievements (
	id SERIAL,
	school VARCHAR(2),
	sex CHAR,
	age SMALLINT,
	address CHAR,
	family_size VARCHAR(3),
	parent_status CHAR,
	mother_education SMALLINT,
	father_education SMALLINT,
	mother_job VARCHAR(16),
	father_job VARCHAR(16),
	reason VARCHAR(16),
	guardian VARCHAR(16),
	travel_time SMALLINT,
	study_time SMALLINT,
	failures SMALLINT,
	school_support BOOLEAN,
	family_support BOOLEAN,
	paid BOOLEAN,
	activities BOOLEAN,
	nursery BOOLEAN,
	higher BOOLEAN,
	internet BOOLEAN,
	romantic BOOLEAN,
	family_relations SMALLINT,
	free_time SMALLINT,
	go_out SMALLINT,
	daily_alcohol SMALLINT,
	weekly_alcohol SMALLINT,
	health SMALLINT,
	absences SMALLINT,
	grade_first SMALLINT,
	grade_second SMALLINT,
	grade_final SMALLINT,
	PRIMARY KEY (id)
);
